Fix argocd login flakiness

diff --git a/test/data/helm-chart/template.yaml b/test/data/helm-chart/template.yaml
--- a/test/data/helm-chart/template.yaml
+++ b/test/data/helm-chart/template.yaml
@@ -694,7 +694,18 @@ spec:
                   echo -n "."
                   ARGOCD_PASSWORD="$(kubectl get secret -n "$NAMESPACE" "$RHTAP_ARGOCD_INSTANCE-cluster" -o jsonpath="{.data.admin\.password}" | base64 --decode)"
                   echo -n "."
-                  ./argocd login "$ARGOCD_HOSTNAME" --grpc-web --insecure --http-retry-max 5 --username admin --password "$ARGOCD_PASSWORD" >/dev/null
+                  RETRY=0
+                  while ! ./argocd login "$ARGOCD_HOSTNAME" --grpc-web --insecure --http-retry-max 5 --username admin --password "$ARGOCD_PASSWORD" >/dev/null; do
+                    if [ "$RETRY" = "20" ]; then
+                      echo "FAIL"
+                      echo "[ERROR] Could not login to ArgoCD" >&2
+                      exit 1
+                    else
+                      echo -n "_"
+                      RETRY=$((RETRY + 1))
+                      sleep 5
+                    fi
+                  done
                   echo -n "."
                   ARGOCD_API_TOKEN="$(./argocd account generate-token --http-retry-max 5 --account "admin")"
                   echo -n "."
