Improve gitops/argocd test
This change should facilitate the troubleshooting of RHTAPBUGS-1161

diff --git a/test/data/helm-chart/template.yaml b/test/data/helm-chart/template.yaml
--- a/test/data/helm-chart/template.yaml
+++ b/test/data/helm-chart/template.yaml
@@ -1701,6 +1701,8 @@ spec:
               set -o nounset
               set -o pipefail
         
+              ERRORS=()
+        
               rollout_status() {
                 local namespace="${1}"
                 local deployment="${2}"
@@ -1711,7 +1713,7 @@ spec:
                 fi
               }
         
-              check_rhtap_gitops_health() {
+              check_gitops_operator_health() {
                 echo "[INFO] Checking OpenShift GitOps health..."
         
                 # wait until tekton pipelines operator is created
@@ -1753,8 +1755,35 @@ spec:
         
                 oc delete ns test-argocd
               }
-              
-              check_rhtap_gitops_health
+        
+              check_rhtap_argocd_health() {
+                echo "[INFO] Checking RHTAP ArgoCD instance health..."
+                # Make sure the rhtap ArgoCD instance has permission on the cluster
+                echo -n "* ArgoCD clusterroles: "
+                if [ "$(oc get clusterroles -o name | grep -c "/rhtap-argocd-")" = "3" ]; then
+                  echo "OK"
+                else
+                  echo "FAIL"
+                  ERRORS+=("ClusterRoles for ArgoCD not found.")
+                fi
+                echo -n "* ArgoCD clusterrolebindings: "
+                if [ "$(oc get clusterrolebindings -o name | grep -c "/rhtap-argocd-")" = "3" ]; then
+                  echo "OK"
+                else
+                  echo "FAIL"
+                  ERRORS+=("ClusterRoleBindings for ArgoCD not found.")
+                fi
+              }
+        
+              check_gitops_operator_health
+              check_rhtap_argocd_health
+        
+              if [ "${#ERRORS[@]}" != "0" ]; then
+                for MSG in "${ERRORS[@]}"; do
+                  echo "[ERROR]$MSG" >&2
+                done
+                exit 1
+              fi
           resources:
             limits:
               cpu: 100m
